<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="Project Test Suite" tests="56" assertions="92" errors="0" failures="11" skipped="0" time="13.409479">
    <testsuite name="Tests\AppBundle\Command\CreateAgentCommandTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Command/CreateAgentCommandTest.php" tests="1" assertions="1" errors="0" failures="0" skipped="0" time="1.381259">
      <testcase name="testExecuteCreateAgentCommand" class="Tests\AppBundle\Command\CreateAgentCommandTest" classname="Tests.AppBundle.Command.CreateAgentCommandTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Command/CreateAgentCommandTest.php" line="54" assertions="1" time="1.381259"/>
    </testsuite>
    <testsuite name="Tests\AppBundle\Controller\AgentControllerTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/AgentControllerTest.php" tests="1" assertions="3" errors="0" failures="0" skipped="0" time="2.643758">
      <testsuite name="Tests\AppBundle\Controller\AgentControllerTest::testLoginAction" tests="1" assertions="3" errors="0" failures="0" skipped="0" time="2.643758">
        <testcase name="testLoginAction with data set #0" class="Tests\AppBundle\Controller\AgentControllerTest" classname="Tests.AppBundle.Controller.AgentControllerTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/AgentControllerTest.php" line="33" assertions="3" time="2.643758"/>
      </testsuite>
    </testsuite>
    <testsuite name="Tests\AppBundle\Controller\BaseControllerTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/BaseControllerTest.php" tests="1" assertions="0" errors="0" failures="1" skipped="0" time="0.031949">
      <testcase name="Warning" assertions="0" time="0.031949">
        <warning type="PHPUnit\Framework\Warning">Warning
No tests found in class "Tests\AppBundle\Controller\BaseControllerTest".

</warning>
      </testcase>
    </testsuite>
    <testsuite name="Tests\AppBundle\Controller\CustomerControllerTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/CustomerControllerTest.php" tests="3" assertions="3" errors="0" failures="3" skipped="0" time="2.347877">
      <testcase name="testGetCustomerListAction" class="Tests\AppBundle\Controller\CustomerControllerTest" classname="Tests.AppBundle.Controller.CustomerControllerTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/CustomerControllerTest.php" line="20" assertions="1" time="1.334247">
        <failure type="PHPUnit\Framework\ExpectationFailedException">Tests\AppBundle\Controller\CustomerControllerTest::testGetCustomerListAction
Failed asserting that 401 matches expected 200.

/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/CustomerControllerTest.php:32
</failure>
      </testcase>
      <testsuite name="Tests\AppBundle\Controller\CustomerControllerTest::testGetCustomerDetailAction" tests="1" assertions="1" errors="0" failures="1" skipped="0" time="0.500348">
        <testcase name="testGetCustomerDetailAction with data set #0" class="Tests\AppBundle\Controller\CustomerControllerTest" classname="Tests.AppBundle.Controller.CustomerControllerTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/CustomerControllerTest.php" line="40" assertions="1" time="0.500348">
          <failure type="PHPUnit\Framework\ExpectationFailedException">Tests\AppBundle\Controller\CustomerControllerTest::testGetCustomerDetailAction with data set #0 (array(1))
Failed asserting that 401 matches expected 200.

/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/CustomerControllerTest.php:52
</failure>
        </testcase>
      </testsuite>
      <testsuite name="Tests\AppBundle\Controller\CustomerControllerTest::testCreateCustomerAction" tests="1" assertions="1" errors="0" failures="1" skipped="0" time="0.513282">
        <testcase name="testCreateCustomerAction with data set #0" class="Tests\AppBundle\Controller\CustomerControllerTest" classname="Tests.AppBundle.Controller.CustomerControllerTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/CustomerControllerTest.php" line="66" assertions="1" time="0.513282">
          <failure type="PHPUnit\Framework\ExpectationFailedException">Tests\AppBundle\Controller\CustomerControllerTest::testCreateCustomerAction with data set #0 (array('Prafulla', '9777096808'))
Failed asserting that 401 matches expected 200.

/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/CustomerControllerTest.php:78
</failure>
        </testcase>
      </testsuite>
    </testsuite>
    <testsuite name="Tests\AppBundle\Controller\OrderControllerTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/OrderControllerTest.php" tests="1" assertions="1" errors="0" failures="1" skipped="0" time="0.613778">
      <testsuite name="Tests\AppBundle\Controller\OrderControllerTest::testPlaceOrderAction" tests="1" assertions="1" errors="0" failures="1" skipped="0" time="0.613778">
        <testcase name="testPlaceOrderAction with data set #0" class="Tests\AppBundle\Controller\OrderControllerTest" classname="Tests.AppBundle.Controller.OrderControllerTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/OrderControllerTest.php" line="22" assertions="1" time="0.613778">
          <failure type="PHPUnit\Framework\ExpectationFailedException">Tests\AppBundle\Controller\OrderControllerTest::testPlaceOrderAction with data set #0 (array(array(array('P001', 2)), array('Prafulla Meher', '9777096808')), 200)
Failed asserting that 401 matches expected 200.

/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/OrderControllerTest.php:34
</failure>
        </testcase>
      </testsuite>
    </testsuite>
    <testsuite name="Tests\AppBundle\Controller\ProductControllerTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/ProductControllerTest.php" tests="5" assertions="5" errors="0" failures="5" skipped="0" time="2.501636">
      <testsuite name="Tests\AppBundle\Controller\ProductControllerTest::testGetProductListAction" tests="2" assertions="2" errors="0" failures="2" skipped="0" time="1.007517">
        <testcase name="testGetProductListAction with data set #0" class="Tests\AppBundle\Controller\ProductControllerTest" classname="Tests.AppBundle.Controller.ProductControllerTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/ProductControllerTest.php" line="24" assertions="1" time="0.505035">
          <failure type="PHPUnit\Framework\ExpectationFailedException">Tests\AppBundle\Controller\ProductControllerTest::testGetProductListAction with data set #0 (array(array(), array(1, 2)), 200)
Failed asserting that 401 matches expected 200.

/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/ProductControllerTest.php:36
</failure>
        </testcase>
        <testcase name="testGetProductListAction with data set #1" class="Tests\AppBundle\Controller\ProductControllerTest" classname="Tests.AppBundle.Controller.ProductControllerTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/ProductControllerTest.php" line="24" assertions="1" time="0.502482">
          <failure type="PHPUnit\Framework\ExpectationFailedException">Tests\AppBundle\Controller\ProductControllerTest::testGetProductListAction with data set #1 (array(array('P001', 'shoes', 'A good shoes', 12.0, 1), array(1, 2)), 200)
Failed asserting that 401 matches expected 200.

/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/ProductControllerTest.php:36
</failure>
        </testcase>
      </testsuite>
      <testsuite name="Tests\AppBundle\Controller\ProductControllerTest::testGetProductDetailAction" tests="1" assertions="1" errors="0" failures="1" skipped="0" time="0.495784">
        <testcase name="testGetProductDetailAction with data set #0" class="Tests\AppBundle\Controller\ProductControllerTest" classname="Tests.AppBundle.Controller.ProductControllerTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/ProductControllerTest.php" line="51" assertions="1" time="0.495784">
          <failure type="PHPUnit\Framework\ExpectationFailedException">Tests\AppBundle\Controller\ProductControllerTest::testGetProductDetailAction with data set #0 (array('P001'), 200)
Failed asserting that 401 matches expected 200.

/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/ProductControllerTest.php:62
</failure>
        </testcase>
      </testsuite>
      <testsuite name="Tests\AppBundle\Controller\ProductControllerTest::testUpdateProductAction" tests="1" assertions="1" errors="0" failures="1" skipped="0" time="0.502058">
        <testcase name="testUpdateProductAction with data set #0" class="Tests\AppBundle\Controller\ProductControllerTest" classname="Tests.AppBundle.Controller.ProductControllerTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/ProductControllerTest.php" line="77" assertions="1" time="0.502058">
          <failure type="PHPUnit\Framework\ExpectationFailedException">Tests\AppBundle\Controller\ProductControllerTest::testUpdateProductAction with data set #0 (array('P001', 12.0, 15.0, 1), 200)
Failed asserting that 401 matches expected 200.

/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/ProductControllerTest.php:88
</failure>
        </testcase>
      </testsuite>
      <testsuite name="Tests\AppBundle\Controller\ProductControllerTest::testCreateProductAction" tests="1" assertions="1" errors="0" failures="1" skipped="0" time="0.496277">
        <testcase name="testCreateProductAction with data set #0" class="Tests\AppBundle\Controller\ProductControllerTest" classname="Tests.AppBundle.Controller.ProductControllerTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/ProductControllerTest.php" line="103" assertions="1" time="0.496277">
          <failure type="PHPUnit\Framework\ExpectationFailedException">Tests\AppBundle\Controller\ProductControllerTest::testCreateProductAction with data set #0 (array('P031', 'bottle', 'Good Product', 12.0, 15.0, 1, 'piece', 1), 200)
Failed asserting that 401 matches expected 200.

/var/www/html/TDD/symfony_3.4/tests/AppBundle/Controller/ProductControllerTest.php:114
</failure>
        </testcase>
      </testsuite>
    </testsuite>
    <testsuite name="Tests\AppBundle\EventListener\RequestListenerTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/EventListener/RequestListenerTest.php" tests="4" assertions="5" errors="0" failures="0" skipped="0" time="0.459745">
      <testsuite name="Tests\AppBundle\EventListener\RequestListenerTest::testRequestListener" tests="4" assertions="5" errors="0" failures="0" skipped="0" time="0.459745">
        <testcase name="testRequestListener with data set #0" class="Tests\AppBundle\EventListener\RequestListenerTest" classname="Tests.AppBundle.EventListener.RequestListenerTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/EventListener/RequestListenerTest.php" line="39" assertions="1" time="0.236809"/>
        <testcase name="testRequestListener with data set #1" class="Tests\AppBundle\EventListener\RequestListenerTest" classname="Tests.AppBundle.EventListener.RequestListenerTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/EventListener/RequestListenerTest.php" line="39" assertions="1" time="0.064861"/>
        <testcase name="testRequestListener with data set #2" class="Tests\AppBundle\EventListener\RequestListenerTest" classname="Tests.AppBundle.EventListener.RequestListenerTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/EventListener/RequestListenerTest.php" line="39" assertions="1" time="0.081437"/>
        <testcase name="testRequestListener with data set #3" class="Tests\AppBundle\EventListener\RequestListenerTest" classname="Tests.AppBundle.EventListener.RequestListenerTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/EventListener/RequestListenerTest.php" line="39" assertions="2" time="0.076638"/>
      </testsuite>
    </testsuite>
    <testsuite name="Tests\AppBundle\EventListener\ResponseListenerTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/EventListener/ResponseListenerTest.php" tests="2" assertions="2" errors="0" failures="0" skipped="0" time="0.133998">
      <testsuite name="Tests\AppBundle\EventListener\ResponseListenerTest::testResponseListener" tests="2" assertions="2" errors="0" failures="0" skipped="0" time="0.133998">
        <testcase name="testResponseListener with data set #0" class="Tests\AppBundle\EventListener\ResponseListenerTest" classname="Tests.AppBundle.EventListener.ResponseListenerTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/EventListener/ResponseListenerTest.php" line="39" assertions="1" time="0.062071"/>
        <testcase name="testResponseListener with data set #1" class="Tests\AppBundle\EventListener\ResponseListenerTest" classname="Tests.AppBundle.EventListener.ResponseListenerTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/EventListener/ResponseListenerTest.php" line="39" assertions="1" time="0.071927"/>
      </testsuite>
    </testsuite>
    <testsuite name="Tests\AppBundle\Repository\CustomerRepositoryTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Repository/CustomerRepositoryTest.php" tests="5" assertions="8" errors="0" failures="0" skipped="0" time="0.737664">
      <testsuite name="Tests\AppBundle\Repository\CustomerRepositoryTest::findAllRecordsTest" tests="3" assertions="6" errors="0" failures="0" skipped="0" time="0.514278">
        <testcase name="findAllRecordsTest with data set #0" class="Tests\AppBundle\Repository\CustomerRepositoryTest" classname="Tests.AppBundle.Repository.CustomerRepositoryTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Repository/CustomerRepositoryTest.php" line="32" assertions="2" time="0.341566"/>
        <testcase name="findAllRecordsTest with data set #1" class="Tests\AppBundle\Repository\CustomerRepositoryTest" classname="Tests.AppBundle.Repository.CustomerRepositoryTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Repository/CustomerRepositoryTest.php" line="32" assertions="2" time="0.087750"/>
        <testcase name="findAllRecordsTest with data set #2" class="Tests\AppBundle\Repository\CustomerRepositoryTest" classname="Tests.AppBundle.Repository.CustomerRepositoryTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Repository/CustomerRepositoryTest.php" line="32" assertions="2" time="0.084962"/>
      </testsuite>
      <testsuite name="Tests\AppBundle\Repository\CustomerRepositoryTest::findOneByIdTest" tests="2" assertions="2" errors="0" failures="0" skipped="0" time="0.223387">
        <testcase name="findOneByIdTest with data set #0" class="Tests\AppBundle\Repository\CustomerRepositoryTest" classname="Tests.AppBundle.Repository.CustomerRepositoryTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Repository/CustomerRepositoryTest.php" line="64" assertions="1" time="0.133926"/>
        <testcase name="findOneByIdTest with data set #1" class="Tests\AppBundle\Repository\CustomerRepositoryTest" classname="Tests.AppBundle.Repository.CustomerRepositoryTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Repository/CustomerRepositoryTest.php" line="64" assertions="1" time="0.089461"/>
      </testsuite>
    </testsuite>
    <testsuite name="Tests\AppBundle\Service\AgentServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/AgentServiceTest.php" tests="7" assertions="9" errors="0" failures="0" skipped="0" time="0.606041">
      <testsuite name="Tests\AppBundle\Service\AgentServiceTest::testGetUser" tests="1" assertions="1" errors="0" failures="0" skipped="0" time="0.067362">
        <testcase name="testGetUser with data set #0" class="Tests\AppBundle\Service\AgentServiceTest" classname="Tests.AppBundle.Service.AgentServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/AgentServiceTest.php" line="33" assertions="1" time="0.067362"/>
      </testsuite>
      <testsuite name="Tests\AppBundle\Service\AgentServiceTest::testValidateUserCredentialsThroughExceptionWithInvalidCredential" tests="1" assertions="1" errors="0" failures="0" skipped="0" time="0.123975">
        <testcase name="testValidateUserCredentialsThroughExceptionWithInvalidCredential with data set #0" class="Tests\AppBundle\Service\AgentServiceTest" classname="Tests.AppBundle.Service.AgentServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/AgentServiceTest.php" line="61" assertions="1" time="0.123975"/>
      </testsuite>
      <testsuite name="Tests\AppBundle\Service\AgentServiceTest::testValidateUserCredentials" tests="1" assertions="1" errors="0" failures="0" skipped="0" time="0.070893">
        <testcase name="testValidateUserCredentials with data set #0" class="Tests\AppBundle\Service\AgentServiceTest" classname="Tests.AppBundle.Service.AgentServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/AgentServiceTest.php" line="113" assertions="1" time="0.070893"/>
      </testsuite>
      <testsuite name="Tests\AppBundle\Service\AgentServiceTest::testValidateUserCredentialsThroughExceptionWithInvalidUserName" tests="1" assertions="1" errors="0" failures="0" skipped="0" time="0.063307">
        <testcase name="testValidateUserCredentialsThroughExceptionWithInvalidUserName with data set #0" class="Tests\AppBundle\Service\AgentServiceTest" classname="Tests.AppBundle.Service.AgentServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/AgentServiceTest.php" line="165" assertions="1" time="0.063307"/>
      </testsuite>
      <testsuite name="Tests\AppBundle\Service\AgentServiceTest::testValidateUserCredentialsThroughExceptionWithDisabledUser" tests="1" assertions="1" errors="0" failures="0" skipped="0" time="0.062592">
        <testcase name="testValidateUserCredentialsThroughExceptionWithDisabledUser with data set #0" class="Tests\AppBundle\Service\AgentServiceTest" classname="Tests.AppBundle.Service.AgentServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/AgentServiceTest.php" line="192" assertions="1" time="0.062592"/>
      </testsuite>
      <testcase name="testGenerateAuthenticationToken" class="Tests\AppBundle\Service\AgentServiceTest" classname="Tests.AppBundle.Service.AgentServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/AgentServiceTest.php" line="217" assertions="1" time="0.088715"/>
      <testsuite name="Tests\AppBundle\Service\AgentServiceTest::testCreateAuthenticationTokenForUser" tests="1" assertions="3" errors="0" failures="0" skipped="0" time="0.129198">
        <testcase name="testCreateAuthenticationTokenForUser with data set #0" class="Tests\AppBundle\Service\AgentServiceTest" classname="Tests.AppBundle.Service.AgentServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/AgentServiceTest.php" line="226" assertions="3" time="0.129198"/>
      </testsuite>
    </testsuite>
    <testsuite name="Tests\AppBundle\Service\AuthenticateAuthorizeServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/AuthenticateAuthorizeServiceTest.php" tests="5" assertions="5" errors="0" failures="0" skipped="0" time="0.318051">
      <testsuite name="Tests\AppBundle\Service\AuthenticateAuthorizeServiceTest::testAuthenticateApiRequest" tests="1" assertions="1" errors="0" failures="0" skipped="0" time="0.067146">
        <testcase name="testAuthenticateApiRequest with data set #0" class="Tests\AppBundle\Service\AuthenticateAuthorizeServiceTest" classname="Tests.AppBundle.Service.AuthenticateAuthorizeServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/AuthenticateAuthorizeServiceTest.php" line="33" assertions="1" time="0.067146"/>
      </testsuite>
      <testsuite name="Tests\AppBundle\Service\AuthenticateAuthorizeServiceTest::testAuthenticateApiRequestShouldThrowExceptionForInvalidContentType" tests="1" assertions="1" errors="0" failures="0" skipped="0" time="0.060289">
        <testcase name="testAuthenticateApiRequestShouldThrowExceptionForInvalidContentType with data set #0" class="Tests\AppBundle\Service\AuthenticateAuthorizeServiceTest" classname="Tests.AppBundle.Service.AuthenticateAuthorizeServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/AuthenticateAuthorizeServiceTest.php" line="67" assertions="1" time="0.060289"/>
      </testsuite>
      <testsuite name="Tests\AppBundle\Service\AuthenticateAuthorizeServiceTest::testAuthenticateApiRequestShouldThrowExceptionForInvalidAuthorization" tests="1" assertions="1" errors="0" failures="0" skipped="0" time="0.061282">
        <testcase name="testAuthenticateApiRequestShouldThrowExceptionForInvalidAuthorization with data set #0" class="Tests\AppBundle\Service\AuthenticateAuthorizeServiceTest" classname="Tests.AppBundle.Service.AuthenticateAuthorizeServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/AuthenticateAuthorizeServiceTest.php" line="89" assertions="1" time="0.061282"/>
      </testsuite>
      <testsuite name="Tests\AppBundle\Service\AuthenticateAuthorizeServiceTest::testAuthenticateApiRequestShouldThrowExceptionForInvalidUser" tests="1" assertions="1" errors="0" failures="0" skipped="0" time="0.066027">
        <testcase name="testAuthenticateApiRequestShouldThrowExceptionForInvalidUser with data set #0" class="Tests\AppBundle\Service\AuthenticateAuthorizeServiceTest" classname="Tests.AppBundle.Service.AuthenticateAuthorizeServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/AuthenticateAuthorizeServiceTest.php" line="111" assertions="1" time="0.066027"/>
      </testsuite>
      <testsuite name="Tests\AppBundle\Service\AuthenticateAuthorizeServiceTest::testAuthenticateApiRequestShouldThrowExceptionForDisabledUser" tests="1" assertions="1" errors="0" failures="0" skipped="0" time="0.063307">
        <testcase name="testAuthenticateApiRequestShouldThrowExceptionForDisabledUser with data set #0" class="Tests\AppBundle\Service\AuthenticateAuthorizeServiceTest" classname="Tests.AppBundle.Service.AuthenticateAuthorizeServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/AuthenticateAuthorizeServiceTest.php" line="144" assertions="1" time="0.063307"/>
      </testsuite>
    </testsuite>
    <testsuite name="Tests\AppBundle\Service\BaseServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/BaseServiceTest.php" tests="1" assertions="0" errors="0" failures="1" skipped="0" time="0.002313">
      <testcase name="Warning" assertions="0" time="0.002313">
        <warning type="PHPUnit\Framework\Warning">Warning
No tests found in class "Tests\AppBundle\Service\BaseServiceTest".

</warning>
      </testcase>
    </testsuite>
    <testsuite name="Tests\AppBundle\Service\CustomerServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/CustomerServiceTest.php" tests="8" assertions="16" errors="0" failures="0" skipped="0" time="0.574827">
      <testsuite name="Tests\AppBundle\Service\CustomerServiceTest::testCreateCustomer" tests="1" assertions="2" errors="0" failures="0" skipped="0" time="0.080496">
        <testcase name="testCreateCustomer with data set #0" class="Tests\AppBundle\Service\CustomerServiceTest" classname="Tests.AppBundle.Service.CustomerServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/CustomerServiceTest.php" line="44" assertions="2" time="0.080496"/>
      </testsuite>
      <testsuite name="Tests\AppBundle\Service\CustomerServiceTest::testGetAllCustomer" tests="3" assertions="6" errors="0" failures="0" skipped="0" time="0.188626">
        <testcase name="testGetAllCustomer with data set #0" class="Tests\AppBundle\Service\CustomerServiceTest" classname="Tests.AppBundle.Service.CustomerServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/CustomerServiceTest.php" line="68" assertions="2" time="0.063479"/>
        <testcase name="testGetAllCustomer with data set #1" class="Tests\AppBundle\Service\CustomerServiceTest" classname="Tests.AppBundle.Service.CustomerServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/CustomerServiceTest.php" line="68" assertions="2" time="0.062532"/>
        <testcase name="testGetAllCustomer with data set #2" class="Tests\AppBundle\Service\CustomerServiceTest" classname="Tests.AppBundle.Service.CustomerServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/CustomerServiceTest.php" line="68" assertions="2" time="0.062615"/>
      </testsuite>
      <testsuite name="Tests\AppBundle\Service\CustomerServiceTest::testGetCustomerDetail" tests="1" assertions="1" errors="0" failures="0" skipped="0" time="0.106703">
        <testcase name="testGetCustomerDetail with data set #0" class="Tests\AppBundle\Service\CustomerServiceTest" classname="Tests.AppBundle.Service.CustomerServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/CustomerServiceTest.php" line="95" assertions="1" time="0.106703"/>
      </testsuite>
      <testsuite name="Tests\AppBundle\Service\CustomerServiceTest::testGetCustomerDetailThrowExceptionForInvalidCustomerId" tests="1" assertions="1" errors="0" failures="0" skipped="0" time="0.063858">
        <testcase name="testGetCustomerDetailThrowExceptionForInvalidCustomerId with data set #0" class="Tests\AppBundle\Service\CustomerServiceTest" classname="Tests.AppBundle.Service.CustomerServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/CustomerServiceTest.php" line="123" assertions="1" time="0.063858"/>
      </testsuite>
      <testsuite name="Tests\AppBundle\Service\CustomerServiceTest::testUpdateCustomerShouldThrowExceptionForInvalidCustomerId" tests="1" assertions="3" errors="0" failures="0" skipped="0" time="0.066859">
        <testcase name="testUpdateCustomerShouldThrowExceptionForInvalidCustomerId with data set #0" class="Tests\AppBundle\Service\CustomerServiceTest" classname="Tests.AppBundle.Service.CustomerServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/CustomerServiceTest.php" line="149" assertions="3" time="0.066859"/>
      </testsuite>
      <testsuite name="Tests\AppBundle\Service\CustomerServiceTest::testUpdateOne" tests="1" assertions="3" errors="0" failures="0" skipped="0" time="0.068285">
        <testcase name="testUpdateOne with data set #0" class="Tests\AppBundle\Service\CustomerServiceTest" classname="Tests.AppBundle.Service.CustomerServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/CustomerServiceTest.php" line="175" assertions="3" time="0.068285"/>
      </testsuite>
    </testsuite>
    <testsuite name="Tests\AppBundle\Service\OrderServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/OrderServiceTest.php" tests="4" assertions="12" errors="0" failures="0" skipped="0" time="0.485238">
      <testsuite name="Tests\AppBundle\Service\OrderServiceTest::testProcessPlaceOrderRequest" tests="1" assertions="4" errors="0" failures="0" skipped="0" time="0.278277">
        <testcase name="testProcessPlaceOrderRequest with data set #0" class="Tests\AppBundle\Service\OrderServiceTest" classname="Tests.AppBundle.Service.OrderServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/OrderServiceTest.php" line="54" assertions="4" time="0.278277"/>
      </testsuite>
      <testsuite name="Tests\AppBundle\Service\OrderServiceTest::testValidatePlaceOrderRequest" tests="1" assertions="2" errors="0" failures="0" skipped="0" time="0.062395">
        <testcase name="testValidatePlaceOrderRequest with data set #0" class="Tests\AppBundle\Service\OrderServiceTest" classname="Tests.AppBundle.Service.OrderServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/OrderServiceTest.php" line="121" assertions="2" time="0.062395"/>
      </testsuite>
      <testsuite name="Tests\AppBundle\Service\OrderServiceTest::testFetchOrCreateCustomer" tests="2" assertions="6" errors="0" failures="0" skipped="0" time="0.144566">
        <testcase name="testFetchOrCreateCustomer with data set #0" class="Tests\AppBundle\Service\OrderServiceTest" classname="Tests.AppBundle.Service.OrderServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/OrderServiceTest.php" line="138" assertions="3" time="0.079776"/>
        <testcase name="testFetchOrCreateCustomer with data set #1" class="Tests\AppBundle\Service\OrderServiceTest" classname="Tests.AppBundle.Service.OrderServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/OrderServiceTest.php" line="138" assertions="3" time="0.064790"/>
      </testsuite>
    </testsuite>
    <testsuite name="Tests\AppBundle\Service\ProductServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/ProductServiceTest.php" tests="8" assertions="22" errors="0" failures="0" skipped="0" time="0.571345">
      <testsuite name="Tests\AppBundle\Service\ProductServiceTest::testFetchProductList" tests="3" assertions="6" errors="0" failures="0" skipped="0" time="0.204761">
        <testcase name="testFetchProductList with data set #0" class="Tests\AppBundle\Service\ProductServiceTest" classname="Tests.AppBundle.Service.ProductServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/ProductServiceTest.php" line="50" assertions="2" time="0.068928"/>
        <testcase name="testFetchProductList with data set #1" class="Tests\AppBundle\Service\ProductServiceTest" classname="Tests.AppBundle.Service.ProductServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/ProductServiceTest.php" line="50" assertions="2" time="0.068164"/>
        <testcase name="testFetchProductList with data set #2" class="Tests\AppBundle\Service\ProductServiceTest" classname="Tests.AppBundle.Service.ProductServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/ProductServiceTest.php" line="50" assertions="2" time="0.067669"/>
      </testsuite>
      <testsuite name="Tests\AppBundle\Service\ProductServiceTest::testCreateProduct" tests="1" assertions="2" errors="0" failures="0" skipped="0" time="0.078240">
        <testcase name="testCreateProduct with data set #0" class="Tests\AppBundle\Service\ProductServiceTest" classname="Tests.AppBundle.Service.ProductServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/ProductServiceTest.php" line="86" assertions="2" time="0.078240"/>
      </testsuite>
      <testsuite name="Tests\AppBundle\Service\ProductServiceTest::testGetProductDetail" tests="1" assertions="3" errors="0" failures="0" skipped="0" time="0.067981">
        <testcase name="testGetProductDetail with data set #0" class="Tests\AppBundle\Service\ProductServiceTest" classname="Tests.AppBundle.Service.ProductServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/ProductServiceTest.php" line="112" assertions="3" time="0.067981"/>
      </testsuite>
      <testsuite name="Tests\AppBundle\Service\ProductServiceTest::testGetProductDetailThrowExceptionForInvalidProductCode" tests="1" assertions="4" errors="0" failures="0" skipped="0" time="0.085478">
        <testcase name="testGetProductDetailThrowExceptionForInvalidProductCode with data set #0" class="Tests\AppBundle\Service\ProductServiceTest" classname="Tests.AppBundle.Service.ProductServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/ProductServiceTest.php" line="141" assertions="4" time="0.085478"/>
      </testsuite>
      <testsuite name="Tests\AppBundle\Service\ProductServiceTest::testUpdateProductThrowExceptionForInvalidProductCode" tests="1" assertions="4" errors="0" failures="0" skipped="0" time="0.064543">
        <testcase name="testUpdateProductThrowExceptionForInvalidProductCode with data set #0" class="Tests\AppBundle\Service\ProductServiceTest" classname="Tests.AppBundle.Service.ProductServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/ProductServiceTest.php" line="169" assertions="4" time="0.064543"/>
      </testsuite>
      <testsuite name="Tests\AppBundle\Service\ProductServiceTest::testUpdateOne" tests="1" assertions="3" errors="0" failures="0" skipped="0" time="0.070342">
        <testcase name="testUpdateOne with data set #0" class="Tests\AppBundle\Service\ProductServiceTest" classname="Tests.AppBundle.Service.ProductServiceTest" file="/var/www/html/TDD/symfony_3.4/tests/AppBundle/Service/ProductServiceTest.php" line="197" assertions="3" time="0.070342"/>
      </testsuite>
    </testsuite>
  </testsuite>
</testsuites>
